version: 0.0
os: linux
files:
 - source: .
   destination: /home/server/
hooks:
  AfterInstall:
   - location: scripts/install
     timeout: 300
     runas: root
  ApplicationStart:
   - location: scripts/start
     timeout: 300
     runas: root