name: Upload Webapp

on:
  push:
    branches: [main]

jobs:
  # continuous-integration:
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Step 1
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     # Step 2
  #     - name: Set up Node
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'
  #     # Step 3
  #     - name: Install dependencies
  #       run: npm install
  #     # Step 4
  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.ACCESS_KEY }}
  #         aws-secret-access-key: ${{ secrets.SECRET_KEY }}
  #         aws-region: us-east-1
    
  continuous-deployment:
    runs-on: ubuntu-latest
    # needs: [continuous-integration]
    if: github.ref == 'refs/heads/main'
    steps:
      # Step 1
      - name: Checkout
        uses: actions/checkout@v2
      # Step 2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-east-1
      # Step 3
      - name: Push code to S3
        run: |
          aws deploy push \
          --application-name csye6225-webapp \
          --description "This is a revision for the webapp" \
          --ignore-hidden-files \
          --s3-location s3://${{ secrets.S3_BUCKET }}/webapp.zip \
          --source .
      # Step 4
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name csye6225-webapp \
            --deployment-group-name csye6225-webapp-deployment \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --description "Node app deployed to ec2" \
            --s3-location bucket=${{ secrets.S3_BUCKET }},bundleType=zip,key=webapp.zip