name: Upload Webapp

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Zip Folder
      run: |
       zip -r release.zip . -x ".git/*" ".github/*" ".gitignore"
       mkdir build
       cp ./release.zip ./build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY }}
        aws-region: us-east-1

    - name: Deploy webapp zip to S3 bucket
      run: aws s3 sync ./build s3://${{ secrets.S3_BUCKET }} --delete